<?php
/**
 * Defines the Constant class used throughout the plugin.
 *
 * @package keywoot-saml-sso\assets\lib
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Defines Error Codes used in the plugin.
 */
class KwErrorCodes {
	/**
	 * Default error message for end-users.
	 *
	 * @return string
	 */
	public static function get_end_user_error() {
		return 'Unable to process your request. Please contact your administrator and provide the error code for assistance.';
	}

	/**
	 * Retrieves detailed error information for a given error code.
	 *
	 * @param string $key The error code key.
	 * @return string|null
	 */
	public static function get_error_details( $key ) {
		return self::$error_codes[ $key ]['DETAILS'] ?? null;
	}
	/**
	 * Map of error codes to their details.
	 *
	 * @var array
	 */
	public static $error_codes = array(
		'ERR_AUTHENTICATION_FAILED' => array(
			'DETAILS' => 'The SAML response lacks a success status, indicating an authentication failure at the Identity Provider (IdP). Please check your IdP configuration and try again.',
		),
		'ERR_ISSUER_MISMATCH' => array(
			'DETAILS' => 'The IDP Issuer/EntityID configured in the plugin does not match the issuer received in the SAML response. Please ensure the correct IDP Issuer/EntityID is configured in the plugin.',
		),
		'ERR_DESTINATION_URL_MISMATCH' => array(
			'DETAILS' => 'The Destination URL received in the response does not match the expected URL. Ensure that you use the correct Destination/ACS URL in the IDP Configuration. You can find the correct Destination/ACS URL in the SP Metadata tab.',
		),
		'ERR_INVALID_TIMESTAMP' => array(
			'DETAILS' => 'Invalid IssueInstant timestamp. The plugin accepts only recently generated responses. Ensure the response from the Identity Provider (IdP) is generated by your request.',
		),
		'ERR_ENCRYPTED_RESPONSE' => array(
			'DETAILS' => 'Encrypted SAML response detected. The free plugin version supports unencrypted responses only. Reconfigure your IdP to send unencrypted responses or upgrade to the premium version for encrypted response support.',
		),
		'ERR_ASSERTION_NOT_DETECTED' => array(
			'DETAILS' => 'Plugin cannot detect the assertion due to an invalid response. Ensure your IdP response includes assertions in the correct format.',
		),
		'ERR_CERTIFICATE_MISMATCH' => array(
			'DETAILS' => 'This error occurs when the certificate configured in the plugin does not match the certificate in the SAML response. Ensure that the correct certificate is configured in the plugin.',
		),
		'ERR_CONDITION_STATEMENT_MISSING' => array(
			'DETAILS' => 'This error occurs when the SAML response does not contain a Condition Statement. Ensure that your IdP response includes Condition statements in the correct format.',
		),
		'ERR_CONDITION_TIME_VALIDITY' => array(
			'DETAILS' => 'The SAML response assertion is invalid due to a Not Before and Not After Condition time validity issue. Ensure that the time on your server and the Identity Provider (IdP) are synchronized.',
		),
		'ERR_AUDIENCE_URI_MISMATCH' => array(
			'DETAILS' => 'Audience URI not configured properly in the Identity Provider (IdP). Copy the Audience URI from the SP Metadata tab and configure it in your IdP.',
		),
		'ERR_DUPLICATE_RESPONSE' => array(
			'DETAILS' => 'This error indicates that the response has already been validated once. Please ensure you initiate a new SAML request and authenticate correctly.',
		),
		'ERR_MISSING_NAMEID_ATTRIBUTE' => array(
			'DETAIL' => 'This error is encountered when the NameID attribute is not found in the IDP response. Ensure your IDP is properly sending the NameID attribute.',
		),
		'ERR_USER_CREATION_FAILED' => array(
			'DETAIL' => 'This error indicates issues in creating a new WordPress user after validation.',
		),
		'ERR_LONG_USERNAME' => array(
			'DETAIL' => 'This error occurs when the Username value exceeds 50 characters. Please configure your Identity Provider (IDP) to send a valid email address as the NameID, ensuring it is less than 50 characters.',
		),
		'ERR_MISSING_OPENSSL_EXTENSION' => array(
			'DETAIL' => 'The plugin requires the OpenSSL extension to work properly',
		),
		'ERR_MISMATCHED_REQUEST_ID' => array(
			'DETAILS' => 'This error indicates that the isResponseTo parameter in the SAML response does not match the request ID, meaning the received response does not correspond to the original request. Please ensure you initiate a new SAML request and authenticate correctly.',
		),
	);
}
